/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class file_engine_uwp_dllInterface_GetIndirectString */

#ifndef _Included_file_engine_uwp_dllInterface_GetIndirectString
#define _Included_file_engine_uwp_dllInterface_GetIndirectString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     file_engine_uwp_dllInterface_GetIndirectString
 * Method:    SHLoadIndirectString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_file_engine_uwp_dllInterface_GetIndirectString_SHLoadIndirectString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
